
services:
  s3:
    image: minio/minio
    container_name: s3
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    networks:
      - TraceSafe-network
    volumes:
      - s3_data:/data


  db:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - config/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
    - TraceSafe-network
    volumes:
      - db_data:/var/lib/postgresql


  tracesafe_backend:
    build: .
    environment:
      - TESTING_LOCAL=false

    networks:
      - TraceSafe-network
    command: python main.py start-api-server
    volumes:
      - ./logs:/app/logs


  reverse-proxy:
    image: nginx:latest
    env_file:
      - config/.env
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - C:\Users\SGCI DATA\Documents\ServeurData\TraceSafe\front:/usr/share/nginx/html
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - TraceSafe-network


volumes:
  db_data:
  s3_data:

networks:
  TraceSafe-network:
    external: true