upstream tracesafe_backend_upstream {
    server tracesafe_backend:${BACKEND_PORT};
}

server {
    listen ${BACKEND_PORT};

    location /api {
        proxy_pass http://tracesafe_backend_upstream;

        client_body_buffer_size 10M;

        proxy_set_header Host $host:$server_port;
        # proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Forwarded-Port $server_port;
    }

    location /healthcheck {
        proxy_pass http://tracesafe_backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
